### ISSUE TITLE
riru core 23.2 magisk 21.2 conflict

### ISSUE THREAD

**Issue by JMViertel85** [Magisk-Modules-Grave/riru_edxposed#2]
Hey with the new Magisk Update and the new riru core update, I can't install riru edexposed yahfa on my phone.  I have riru core 23.2 installed, but am unable to install riru edexposed yahfa 4.6.4. I am using a moto z2 force.  Can you please find a fix or tell me how to fix it?  The new magisk 21.2 will not allow me to use older versions of riru core and yahfa edexposed.

**Comment by JMViertel85** [comment]
[Uploading EdXposed-YAHFA-v0.5.1.4_4655-master-debug(1).zip…]()

**Comment by JMViertel85** [comment]
Copying zip to temp directory
- Installing Riru_-_EdXposed-v0.4.6.4_(4563)_(YAHFA)(4563).zip
- Current boot slot: _a
- Device is system-as-root
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: module.prop
*******************************
 Riru - EdXposed 
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: customize.sh
 by solohsu, MlgmXyysd & rk700 
*******************************
*******************
 Powered by Magisk 
*******************
- EdXposed Version v0.4.6.4 (4563) (YAHFA)
- Android sdk: 29
- Magisk version: 21200
******************************
! Requirement module 'Riru - Core' is not installed
! or unsupported v22+ is installed, use v21.3 instead
! You can download from 'Magisk Manager' or https://github.com/RikkaApps/Riru/releases
******************************
! Installation failed

**Comment by 7wells** [comment]
Hello! I have the same issue (with the same a/mentioned message about the requirement) on a Google Nexus 4 (mako with LOS 17.1).

**Comment by JasonKhew96** [comment]
https://github.com/ElderDrivers/EdXposed/issues/665

**Comment by 7wells** [comment]
After flashing https://github.com/RikkaApps/Riru/releases/tag/v21.3 via Magisk manager, I could also flash Riru EdXposed v0.4.6.4.
